language: node_js
sudo: false
node_js:
  - '6'
  - '5'
  - '4'
before_install:
  - npm install -g gulp
after_success:
  - gulp ci
deploy:
  provider: npm
  email: contact@tiste.org
  api_key:
    secure: S+uy6h86WWxQPqk6yzDNZil3clKlDeKYea/SWHFedSMS1IifS+9A07RzTxCGIwxBkgM/jhcX0H0WH22LyjMTM7nzOWi+Ry/fIB4OWS3QBRWXyh5Ft7ydHX42G9oKGhOnxu47qBGbcudByVdAMVG0xvSCIRfyc9BWB5KzKIYm53U=
  on:
    tags: true
    all_branches: true
