language: node_js
sudo: false
node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'
before_install:
  - npm install -g gulp
after_success:
  - gulp ci
addons:
  code_climate:
    repo_token: 39bfa58007837b1cb6b5792bebd0b802dd4c545ecb7d311a5a276a174b4b3910
deploy:
  provider: npm
  email: contact@tiste.org
  api_key:
    secure: S+uy6h86WWxQPqk6yzDNZil3clKlDeKYea/SWHFedSMS1IifS+9A07RzTxCGIwxBkgM/jhcX0H0WH22LyjMTM7nzOWi+Ry/fIB4OWS3QBRWXyh5Ft7ydHX42G9oKGhOnxu47qBGbcudByVdAMVG0xvSCIRfyc9BWB5KzKIYm53U=
  on:
    tags: true
    all_branches: true
