language: node_js
sudo: false
node_js:
  - 0.10
  - 0.12
  - 4
  - 5
before_install:
  - npm install -g gulp
after_success:
  - gulp ci
addons:
  code_climate:
    repo_token: 
      secure: dXSHB/la5xsevu9btEbmjydHrUzrUGPrv11jDWrwqinXtW92/oraASlKdXVNt/x7v+GhNYx4QfR9dINFyvM1kC2HtdsoborsNRvq5ad1mZvGNGKfTEpObCQh2mfbt9RJccBLVCclKQ9c21qu+CJ7IIHunbIj/otJq9bZFsAPusY=
deploy:
  provider: npm
  email: contact@tiste.org
  api_key:
    secure: S+uy6h86WWxQPqk6yzDNZil3clKlDeKYea/SWHFedSMS1IifS+9A07RzTxCGIwxBkgM/jhcX0H0WH22LyjMTM7nzOWi+Ry/fIB4OWS3QBRWXyh5Ft7ydHX42G9oKGhOnxu47qBGbcudByVdAMVG0xvSCIRfyc9BWB5KzKIYm53U=
  on:
    tags: true
    all_branches: true
